apiVersion: v1
kind: Service
metadata:
  name: price-tracker-frontend
  namespace: price-tracker
spec:
  selector:
    app: price-tracker-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
