/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Le processus répond */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Le service peut traiter des requêtes (MongoDB joignable) */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mots-clés suivis, avec nombre de produits et dernier scrape */
        get: operations["KeywordController_list"];
        put?: never;
        /** Suivre un nouveau mot-clé (ou réactiver un mot-clé retiré) */
        post: operations["KeywordController_track"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/{keyword}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Retirer un mot-clé du suivi */
        delete: operations["KeywordController_untrack"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compteurs globaux et meilleures affaires par mot-clé */
        get: operations["DashboardController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/{keyword}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Produits d'un mot-clé, filtrés, triés et paginés */
        get: operations["KeywordProductsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fiche produit complète avec historique de prix */
        get: operations["ProductController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** URLs suivies individuellement, avec dernier prix connu */
        get: operations["ProductTrackingController_list"];
        put?: never;
        /** Suivre une URL produit (ou réactiver une URL retirée) */
        post: operations["ProductTrackingController_track"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-urls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Retirer une URL du suivi individuel */
        delete: operations["ProductTrackingController_untrack"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Produits favoris, fiche complète avec historique de prix */
        get: operations["FavoriteController_list"];
        put?: never;
        /** Mettre un produit en favori (idempotent, suit aussi son prix) */
        post: operations["FavoriteController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie si un produit est en favori */
        get: operations["FavoriteController_check"];
        put?: never;
        post?: never;
        /** Retirer un produit des favoris (idempotent) */
        delete: operations["FavoriteController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KeywordSummaryResponse: {
            /** @example lessive liquide */
            keyword: string;
            /**
             * @description Produits distincts remontés pour ce mot-clé
             * @example 42
             */
            productCount: number;
            /**
             * @description Dernier passage du scrapper, null si aucun produit
             * @example 2026-08-08T06:00:00.000Z
             */
            lastScrape: string | null;
        };
        TrackKeywordDto: {
            /** @example lessive liquide */
            keyword: string;
        };
        MoneyResponse: {
            /** @example 12.99 */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        UnitPriceResponse: {
            /** @example 3.42 */
            amount: number;
            /** @example L */
            unit: string;
        };
        ProductSummaryResponse: {
            /** @description Identifiant encodé, à utiliser dans /products/{id} */
            id: string;
            /** @example https://www.amazon.fr/dp/B0XXXXXXX */
            url: string;
            keyword: string | null;
            /** @example amazon */
            shop: string;
            title: string;
            images: string[];
            price: components["schemas"]["MoneyResponse"] | null;
            crossedOutPrice: components["schemas"]["MoneyResponse"] | null;
            unitPrice: components["schemas"]["UnitPriceResponse"] | null;
            /** @example Livraison lundi 11 août */
            deliveryDate: string | null;
            /** @description ISO 8601 */
            scrapedAt: string;
            /** @description Écart au prix attendu en %, null si le produit manque d’historique */
            dealScore: number | null;
            /** @description Moyenne glissante 30 jours */
            predictedPrice: number | null;
            /** @enum {string|null} */
            trendDirection: "up" | "down" | "stable" | null;
            /** @description Verdict de la politique « bonne affaire », déjà appliqué */
            isDeal: boolean;
        };
        KeywordDealsResponse: {
            keyword: string;
            productCount: number;
            totalDeals: number;
            /** @description Les meilleures seulement */
            deals: components["schemas"]["ProductSummaryResponse"][];
        };
        DashboardResponse: {
            keywordCount: number;
            productCount: number;
            dealCount: number;
            /** @description Dernière exécution du pipeline */
            lastUpdate: string | null;
            dealsByKeyword: components["schemas"]["KeywordDealsResponse"][];
        };
        ProductSearchResponse: {
            items: components["schemas"]["ProductSummaryResponse"][];
            /** @description Produits correspondant aux filtres */
            total: number;
            pageCount: number;
            /** @description Produits du mot-clé, filtres ignorés */
            keywordTotal: number;
            /** @description Bonnes affaires du mot-clé, filtres ignorés */
            keywordDealCount: number;
        };
        PriceHistoryEntryResponse: {
            /** @description ISO 8601 */
            day: string;
            price: components["schemas"]["MoneyResponse"] | null;
            crossedOutPrice: components["schemas"]["MoneyResponse"] | null;
            unitPrice: components["schemas"]["UnitPriceResponse"] | null;
            /** @description ISO 8601 */
            scrapedAt: string;
        };
        ProductDetailResponse: {
            /** @description Identifiant encodé, à utiliser dans /products/{id} */
            id: string;
            /** @example https://www.amazon.fr/dp/B0XXXXXXX */
            url: string;
            keyword: string | null;
            /** @example amazon */
            shop: string;
            title: string;
            images: string[];
            price: components["schemas"]["MoneyResponse"] | null;
            crossedOutPrice: components["schemas"]["MoneyResponse"] | null;
            unitPrice: components["schemas"]["UnitPriceResponse"] | null;
            /** @example Livraison lundi 11 août */
            deliveryDate: string | null;
            /** @description ISO 8601 */
            scrapedAt: string;
            /** @description Écart au prix attendu en %, null si le produit manque d’historique */
            dealScore: number | null;
            /** @description Moyenne glissante 30 jours */
            predictedPrice: number | null;
            /** @enum {string|null} */
            trendDirection: "up" | "down" | "stable" | null;
            /** @description Verdict de la politique « bonne affaire », déjà appliqué */
            isDeal: boolean;
            history: components["schemas"]["PriceHistoryEntryResponse"][];
            firstSeen: string | null;
            lastSeen: string | null;
        };
        TrackedUrlPriceResponse: {
            /** @example 12.99 */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        TrackedUrlSummaryResponse: {
            /** @description Identifiant encodé, à utiliser dans /product-urls/{id} et /products/{id} */
            id: string;
            /** @example https://www.amazon.fr/dp/B0XXXXXXXX/ */
            url: string;
            title: string | null;
            image: string | null;
            price: components["schemas"]["TrackedUrlPriceResponse"] | null;
            /** @description Dernier passage du scrapper, null si pas encore scrapée */
            lastScrape: string | null;
        };
        TrackProductUrlDto: {
            /** @example https://www.amazon.fr/dp/B0XXXXXXXX/ */
            url: string;
        };
        FavoriteStatusResponse: {
            isFavorite: boolean;
        };
        AddFavoriteDto: {
            /** @description Identifiant produit encodé, renvoyé par /products/{id} ou une liste */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KeywordController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordSummaryResponse"][];
                };
            };
        };
    };
    KeywordController_track: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackKeywordDto"];
            };
        };
        responses: {
            /** @description Mot-clé suivi */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nom vide ou trop long */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mot-clé déjà suivi */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KeywordController_untrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mot-clé retiré */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mot-clé inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    KeywordProductsController_search: {
        parameters: {
            query?: {
                /** @description Recherche plein texte sur le titre */
                q?: string;
                /** @description Bonnes affaires uniquement */
                deals?: "1" | "0";
                /** @description Prix minimum */
                min?: string;
                /** @description Prix maximum */
                max?: string;
                sort?: "deals" | "price_asc" | "price_desc" | "discount";
                /** @description Page, à partir de 1 */
                page?: string;
            };
            header?: never;
            path: {
                keyword: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchResponse"];
                };
            };
            /** @description Paramètre de filtre invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant encodé renvoyé par les listes */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            /** @description Identifiant mal formé */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produit inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductTrackingController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedUrlSummaryResponse"][];
                };
            };
        };
    };
    ProductTrackingController_track: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackProductUrlDto"];
            };
        };
        responses: {
            /** @description URL suivie */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description URL absente ou non reconnue comme fiche produit amazon.fr */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description URL déjà suivie */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductTrackingController_untrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant encodé renvoyé par la liste */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL retirée */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identifiant mal formé */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description URL inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoriteController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"][];
                };
            };
        };
    };
    FavoriteController_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFavoriteDto"];
            };
        };
        responses: {
            /** @description Produit favori */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identifiant mal formé */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoriteController_check: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant encodé du produit */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteStatusResponse"];
                };
            };
            /** @description Identifiant mal formé */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoriteController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant encodé du produit */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favori retiré */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identifiant mal formé */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
